# Generated by Django 4.2.1 on 2023-05-23 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubThread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("view_id", models.CharField(max_length=10)),
                ("title", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Sub Threads",
                "db_table": "lb_sub_threads",
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.TextField()),
                ("db_flag", models.CharField(max_length=50)),
                ("label", models.CharField(blank=True, max_length=50, null=True)),
                ("validate", models.IntegerField(default=0)),
                (
                    "validate_url",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[("PUSH", "PUSH"), ("PULL", "PULL")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("action_url", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name_plural": "Thread", "db_table": "lb_threads",},
        ),
        migrations.CreateModel(
            name="ThreadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("WHATSAPP", "Whatsapp")],
                        default="WHATSAPP",
                        max_length=50,
                    ),
                ),
                ("flag", models.CharField(blank=True, max_length=100, null=True)),
                ("values", models.TextField(blank=True, null=True)),
                ("active", models.IntegerField(default=0)),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="thread.thread",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Thread Sessions",
                "db_table": "lb_thread_sessions",
            },
        ),
        migrations.CreateModel(
            name="ThreadLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link",
                        to="thread.thread",
                    ),
                ),
                (
                    "sub_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="thread.subthread",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread",
                        to="thread.thread",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Thread Links",
                "db_table": "lb_thread_links",
            },
        ),
        migrations.AddField(
            model_name="subthread",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="thread.thread"
            ),
        ),
    ]
