# Generated by Django 4.2.1 on 2023-05-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thread", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subthread",
            name="show",
            field=models.CharField(
                choices=[("NUMBER", "Number"), ("BUTTON", "Button")],
                default="NUMBER",
                max_length=20,
            ),
        ),
    ]
