# Generated by Django 4.2.1 on 2023-05-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thread", "0002_subthread_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="subthread",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="subthread",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="thread", name="block", field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="thread",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="thread",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="threadlink",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="threadlink",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="threadsession",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="threadsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
