# Generated by Django 4.2.1 on 2023-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("thread", "0003_subthread_created_at_subthread_updated_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, unique=True)),
                (
                    "id_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NIN", "NIN"),
                            ("DL", "DRIVER LICENCE"),
                            ("VID", "VOTE ID"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PENDING", "PENDING"),
                            ("COMPLETED", "COMPLETED"),
                            ("VALID", "VALID"),
                            ("INVALID", "INVALID"),
                        ],
                        default="PENDING",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer",
                "verbose_name_plural": "Customer",
                "db_table": "lb_customers",
                "managed": True,
            },
        ),
    ]
